#!/bin/bash
# A script to update /etc/hosts, local IP address, hostname, and route.

# Ensure this script runs as root.
test "$(id -u)" -eq 0 || exit 1

# Get the primary network device.
devc=$(ip link | sed -ne 's/^[0-9]\+: *\([^:]\+\): *<BROADCAST.*$/\1/p')

# Fetch the landing-zone IP.
land="${1}"

# Called with only one argument = delete landing-zone ip.
test -z "$2" && ip addr del "${land}" dev "${devc}" && exit 0

# Fetch the gateway, subnet, and domain name.
gatw="${2}"
subn="${3}"
domn="${4}"

shift 4

# Populate /etc/hosts with a list of IP addresses and hostnames.
cat >/etc/hosts <<EOF
127.0.0.1 localhost4.localdomain4 localhost4 localhost.localdomain localhost
::1       localhost6.localdomain6 localhost6 localhost.localdomain localhost
EOF

while test -n "${1}" && test -n "${2}"
do
  addr="${1}"
  host="${2}"
  cp /etc/hosts /etc/hosts.bak
  grep -v "^${addr} " /etc/hosts.bak >/etc/hosts
  echo "${addr} ${host}.${domn} ${host}" >>/etc/hosts
  shift 2
done

# The last given IP/Host pair belongs to this host.

# Add the (new) local IP address.
ip addr add "${addr}/${subn}" dev "${devc}"

# Add the default route.
ip route add default via inet "${gatw}"

# Set the hostname.
hostname "${host}"

# Write /etc/hostname.
hostname -f >/etc/hostname

# Write the ifcfg file.
cat >"/etc/sysconfig/network-scripts/ifcfg-${devc}" <<EOF
BOOTPROTO=none
BROWSER_ONLY=no
DEFROUTE=yes
DEVICE=${devc}
GATEWAY=${gatw}
IPADDR=${addr}
IPV4_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6_AUTOCONF=no
IPV6_DEFROUTE=no
IPV6_FAILURE_FATAL=no
IPV6INIT=no
NAME=${devc}
ONBOOT=yes
PREFIX=21
PROXY_METHOD=none
TYPE=Ethernet
EOF
