#!/bin/bash
# A script to update /etc/hosts, local IP address, hostname, and route.

# Ensure this script runs as root.

test "$(id -u)" -eq 0 || exec sudo -E "$0" "$@"

# Fetch the landing-ip, gateway, subnet, and domain name.

land=$1
gatw=$2
subn=$3
domn=$4

shift 4

# Populate /etc/hosts with a list of IP addresses and hostnames.

while test "$1" -a test "$2"
do
  addr=$1
  host=$2
  cp /etc/hosts /etc/hosts.bak
  grep -v "^${addr} " /etc/hosts.bak >/etc/hosts
  echo "${addr} ${host}.${domn} ${host}" >>/etc/hosts
  shift 2
done

# The last given IP/Host pair belongs to this host.

# Get the primary network device.

devc=$(ip link | sed -ne 's/^[0-9]\+: *\([^:]\+\): *<BROADCAST.*$/\1/p')

# Add the (new) local IP address.

ip addr add "${addr}/${subn}" dev "${devc}"

# Add the default route.

ip route add 0.0.0.0/0 via inet "${gatw}"

# Set the hostname.

hostname "${host}"

# Write /etc/hostname.

hostname -f >/etc/hostname

# Write the ifcfg file.

cat >"/etc/sysconfig/network-scripts/ifcfg-${devc}" <<EOF
BOOTPROTO=none
BROWSER_ONLY=no
DEFROUTE=yes
DEVICE=${devc}
GATEWAY=${gatw}
IPADDR=${addr}
IPV4_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6_AUTOCONF=no
IPV6_DEFROUTE=no
IPV6_FAILURE_FATAL=no
IPV6INIT=no
NAME=${devc}
ONBOOT=yes
PREFIX=21
PROXY_METHOD=none
TYPE=Ethernet
EOF

# Unassign the landing-zone IP just before exiting.

/bin/bash -c "sleep 1; ip addr del ${land}/${subn} dev ${devc}" & exit 0
